### ISSUE TITLE
Java Implementation Code

### ISSUE THREAD

**Issue by mamdooh8** [oleavr/android-inject-custom#1]
Hi ..
Can you provide how can I put my java code here .. 
I use java implementation code .. and it work successfully in ubuntu ( my android device connect via USB )
but how can I use it here ? 
the "agent.c" file written in C 
and also "inject.c" file 
how can I insert my java code ?
regards ..

**Comment by qq782645210** [comment]
how to build it ,the environment is ?
help me!
i cannot build it in win10 ndk20

**Comment by oleavr** [comment]
@mamdooh8 That's beyond the scope of this example. Have a look at the example in our GumJS devkit – you can grab it from our releases page.
