### ISSUE TITLE
i can't build this ? why?

### ISSUE THREAD

**Issue by qq782645210** [oleavr/android-inject-custom#3]
i can't build this ? why? i'm in win10 ,ndk20,down your source,and build like you say
but it's make error=-1
can you make a ndk-build script ?
thank you

**Comment by qq782645210** [comment]
or can you say how to build it step by step
i'm a new program man in linux,please help me.

**Comment by oleavr** [comment]
This example only covers UNIX platforms for now. PRs welcome!
